// Findings normalization, A–F grading, and output formatters (text/json/markdown/summary).

export const SEVERITY_WEIGHTS = {
  critical: 100,
  high: 60,
  medium: 30,
  low: 10,
  info: 3,
};

export const SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"];

export function gradeOf(findings) {
  const score = Math.min(
    600,
    findings.reduce((sum, f) => sum + (SEVERITY_WEIGHTS[f.severity] ?? 0), 0)
  );
  let grade = "A";
  if (score >= 250) grade = "F";
  else if (score >= 100) grade = "E";
  else if (score >= 60) grade = "D";
  else if (score >= 20) grade = "C";
  else if (score >= 1) grade = "B";
  return { grade, score };
}

export function summarize(findings) {
  const bySeverity = Object.fromEntries(SEVERITY_ORDER.map((s) => [s, 0]));
  for (const f of findings) bySeverity[f.severity] = (bySeverity[f.severity] ?? 0) + 1;
  const { grade, score } = gradeOf(findings);
  return { count: findings.length, bySeverity, score, grade };
}

export function formatText(report) {
  const lines = [];
  lines.push(`AgentGuard — ${report.repo} — grade ${report.summary.grade} (score ${report.summary.score})`);
  for (const f of report.findings) {
    lines.push(`  [${f.severity.toUpperCase().padEnd(8)}] ${f.id}  ${f.file}  — ${f.description}`);
    if (f.evidence) lines.push(`            evidence: ${f.evidence}`);
  }
  return lines.join("\n");
}

export function formatJson(report) {
  return JSON.stringify(report, null, 2);
}

export function formatMarkdown(report) {
  const esc = (s) => String(s).replace(/\|/g, "\\|");
  const rows = report.findings
    .map(
      (f) =>
        `| ${f.severity} | \`${esc(f.id)}\` | \`${esc(f.file)}\` | ${esc(f.description)} |`
    )
    .join("\n");
  return `# AgentGuard report — ${report.repo}

**Grade: ${report.summary.grade}** (score ${report.summary.score}) · ${report.summary.count} findings

| Severity | Rule | File | Description |
|---|---|---|---|
${rows || "| - | - | - | No findings |"}

> Generated by AgentGuard at ${report.timestamp}.`;
}

// GitHub Actions usable summary (for $GITHUB_STEP_SUMMARY).
export function formatStepSummary(report) {
  const esc = (s) => String(s).replace(/\|/g, "\\|");
  const rows = report.findings
    .slice(0, 50)
    .map(
      (f) =>
        `| ${f.severity} | \`${esc(f.id)}\` | \`${esc(f.file)}\` | ${esc(f.description)} |`
    )
    .join("\n");
  const hidden = report.findings.length - 50;
  return `### AgentGuard scan — grade ${report.summary.grade} (score ${report.summary.score})

| Severity | Rule | File | Description |
|---|---|---|---|
${rows || "| - | - | - | No findings |"}
${hidden > 0 ? `\n_… ${hidden} more findings_` : ""}

_Generated by AgentGuard_`;
}

export function formatByOption(report, format) {
  switch (format) {
    case "json":
      return formatJson(report);
    case "md":
    case "markdown":
      return formatMarkdown(report);
    case "summary":
      return formatStepSummary(report);
    default:
      return formatText(report);
  }
}
